CREATE DATABASE xdc01_management;
USE xdc01_management;

CREATE TABLE `sys_product_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rn` varchar(30) DEFAULT '',
  `work_order` varchar(45) DEFAULT '' COMMENT '工单批号',
  `token` varchar(255) DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `sys_token` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `token` varchar(255) DEFAULT '',
  `product_id` varchar(30) DEFAULT '',
  `product_name` varchar(30) DEFAULT '',
  `factory_id` varchar(30) DEFAULT '',
  `factory_name` varchar(30) DEFAULT '',
  `model_id` varchar(30) DEFAULT '',
  `model_name` varchar(30) DEFAULT '',
  `color_id` varchar(30) DEFAULT '',
  `color_name` varchar(30) DEFAULT '',
  `rf_type` varchar(30) DEFAULT '' COMMENT 'RF频率 345/433',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `sys_work_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `work_order` varchar(45) DEFAULT '' COMMENT '工单批号',
  `project_name` varchar(30) DEFAULT '',
  `stage` varchar(30) DEFAULT '' COMMENT '项目阶段',
  `factory_name` varchar(30) DEFAULT '',
  `factory_time_zone` varchar(30) DEFAULT '' COMMENT '工厂所在时区',
  `order_info` varchar(45) DEFAULT '' COMMENT '本工单所属的订单号',
  `customer` varchar(30) DEFAULT '' COMMENT '客户',
  `description` varchar(255) DEFAULT '' COMMENT '工单描述',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t010_test_report` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`software_version` VARCHAR (30) DEFAULT '' COMMENT '产测软件版本',
	`spec_id` INT (11) DEFAULT NULL COMMENT '测试规格编号',
	`standard_id` INT (11) DEFAULT NULL COMMENT '版本标准编号',
	`fixture_id` VARCHAR (30) DEFAULT '' COMMENT '测试设备编号',
	`operator_id` VARCHAR (30) DEFAULT '' COMMENT '操作员编号',
	`rn` VARCHAR (30) NOT NULL COMMENT 'RN号',
	`start_test_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`end_test_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`stage_name` VARCHAR (30) NOT NULL COMMENT '阶段',
	`test_mode` VARCHAR (30) NOT NULL COMMENT '测试模式',
	`test_result` VARCHAR (30) NOT NULL COMMENT '测试结果',
	`ng_items` VARCHAR (500) DEFAULT '' COMMENT 'NG测项列表',
	`read_tagnumber` VARCHAR (30) DEFAULT '',
	`write_tagnumber` VARCHAR (30) DEFAULT '',
	`fw_version` VARCHAR (10) DEFAULT '' COMMENT '固件版本',
	`hw_version` VARCHAR (10) DEFAULT '' COMMENT '硬件版本',
	`mcu_version` VARCHAR (10) DEFAULT '' COMMENT 'MCU版本',
	`battery_voltage` FLOAT DEFAULT NULL COMMENT '电池电压读数',
	`cpu_temperature` FLOAT DEFAULT NULL COMMENT '成品温度读数',
	`voltage_wifi` float DEFAULT NULL COMMENT 'Wi-Fi模组电压',
	`voltage_vcc_core` float DEFAULT NULL COMMENT '电压_vcc_core',
	`voltage_sensor1` float DEFAULT NULL COMMENT '电压传感器1',
	`voltage_sensor2` float DEFAULT NULL COMMENT '电压传感器2',
	`voltage_rtc` float DEFAULT NULL COMMENT '电压_rtc',
	`voltage_vcc` float DEFAULT NULL COMMENT 'vcc电压',
	`voltage_mcu` float DEFAULT NULL COMMENT 'MCU电压',
	`voltage_ddr` float DEFAULT NULL COMMENT 'DDR电压',
	`work_current` float DEFAULT NULL COMMENT '工作电流',
	`charge_current` float DEFAULT NULL COMMENT '充电电流',
	`standby_current` float DEFAULT NULL COMMENT '漏电流',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t020_focus_test_rtos` (
	`id` INT (11) NOT NULL AUTO_INCREMENT,
	`software_version` VARCHAR (30) DEFAULT '' COMMENT '产测软件版本',
	`spec_id` INT (11) DEFAULT NULL COMMENT '测试规格编号',
	`standard_id` INT (11) DEFAULT NULL COMMENT '版本标准编号',
	`fixture_id` VARCHAR (30) DEFAULT '' COMMENT '测试设备编号',
	`operator_id` VARCHAR (30) DEFAULT '' COMMENT '操作员编号',
	`rn` VARCHAR (30) NOT NULL COMMENT 'RN号',
	`start_test_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`end_test_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`stage_name` VARCHAR (30) NOT NULL COMMENT '阶段',
	`test_mode` VARCHAR (30) NOT NULL COMMENT '测试模式',
	`test_result` VARCHAR (30) NOT NULL COMMENT '测试结果',
	`ng_items` VARCHAR (500) DEFAULT '' COMMENT 'NG测项列表',
	`read_tagnumber` VARCHAR (30) DEFAULT '',
	`write_tagnumber` VARCHAR (30) DEFAULT '',
	`day_video_check` VARCHAR (30) NOT NULL COMMENT '白天清晰度检查',
	`day_video_photo` VARCHAR (255) DEFAULT '' COMMENT '白天镜头画面截图',
	`dark_corner` VARCHAR (16) DEFAULT '' COMMENT '镜头暗角检查',
	`ir_cut` VARCHAR (30) NOT NULL COMMENT 'IR切换',
	`ir_led` VARCHAR (30) NOT NULL COMMENT 'IR LED灯',
	`night_video_check` VARCHAR (30) NOT NULL COMMENT '夜视清晰度检查',
	`night_video_photo` VARCHAR (255) DEFAULT '' COMMENT '夜视镜头画面截图',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t030_product_test_report` (
	`id` INT (11) NOT NULL AUTO_INCREMENT,
	`software_version` VARCHAR (30) DEFAULT '' COMMENT '产测软件版本',
	`spec_id` INT (11) DEFAULT NULL COMMENT '测试规格编号',
	`standard_id` INT (11) DEFAULT NULL COMMENT '版本标准编号',
	`fixture_id` VARCHAR (30) DEFAULT '' COMMENT '测试设备编号',
	`operator_id` VARCHAR (30) DEFAULT '' COMMENT '操作员编号',
	`rn` VARCHAR (30) NOT NULL COMMENT 'RN号',
	`start_test_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`end_test_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`stage_name` VARCHAR (30) NOT NULL COMMENT '阶段',
	`test_mode` VARCHAR (30) NOT NULL COMMENT '测试模式',
	`test_result` VARCHAR (30) NOT NULL COMMENT '测试结果',
	`ng_items` VARCHAR (500) DEFAULT '' COMMENT 'NG测项列表',
	`read_tagnumber` VARCHAR (30) DEFAULT '',
	`write_tagnumber` VARCHAR (30) DEFAULT '',
	`ping_rtt` FLOAT DEFAULT NULL COMMENT 'Ping的平均延迟',
	`mic_auto` VARCHAR (16) DEFAULT '' COMMENT '自动判定mic结果',
	`mic_data` VARCHAR (30) DEFAULT '' COMMENT '自动测试数据',
	`mic_manual` VARCHAR (16) DEFAULT '' COMMENT '人工判定mic结果',
	`led_color` VARCHAR (16) DEFAULT '' COMMENT 'Button Led颜色检查',
	`motion` VARCHAR (16) DEFAULT '' COMMENT 'PIR测试',
	`button` VARCHAR (16) DEFAULT '' COMMENT '按键功能检查',
	`audio` VARCHAR (16) DEFAULT '' COMMENT '成品喇叭测试',
	`fw_version` VARCHAR (10) DEFAULT '' COMMENT '固件版本',
	`hw_version` VARCHAR (10) DEFAULT '' COMMENT '硬件版本',
	`mcu_version` VARCHAR (10) DEFAULT '' COMMENT 'MCU版本',
	`battery_voltage` FLOAT DEFAULT NULL COMMENT '电池电压读数',
	`cpu_temperature` FLOAT DEFAULT NULL COMMENT '成品温度读数',
	`light` VARCHAR (16) DEFAULT '' COMMENT '成品亮度读数',
	`vlc_rtsp` VARCHAR (16) DEFAULT '' COMMENT '实时影像',
	`ir_cut` VARCHAR (16) DEFAULT '' COMMENT 'IR切换',
	`ir_led` VARCHAR (16) DEFAULT '' COMMENT 'IR LED灯',
	`wifi_up_loss` FLOAT DEFAULT NULL COMMENT '上行丢包率',
	`wifi_up_rate` FLOAT DEFAULT NULL COMMENT '上行速率',
	`up_rate_revise` FLOAT DEFAULT NULL COMMENT '上行速率修正值',
	`wifi_down_loss` FLOAT DEFAULT NULL COMMENT '下行丢包率',
	`wifi_down_rate` FLOAT DEFAULT NULL COMMENT '下行速率',
	`down_rate_revise` FLOAT DEFAULT NULL COMMENT '下行速率修正值',
	`rf_rx` VARCHAR (16) DEFAULT '' COMMENT 'RF接收灵敏度测试',
	`rf_tx_frenquency` FLOAT DEFAULT NULL COMMENT 'RF发送频率',
	`rf_tx_power` FLOAT DEFAULT NULL COMMENT 'RF发送功率',
	`rf_tx_power_revise` FLOAT DEFAULT NULL COMMENT 'RF发送功率修正值',
	`reset_button` VARCHAR (16) DEFAULT '' COMMENT '复位键功能检查',
	`factory_reset` VARCHAR (16) DEFAULT '' COMMENT '恢复出厂设置',
	`mac` VARCHAR (30) DEFAULT '' COMMENT '读取旧MAC',
	`sn` VARCHAR (30) DEFAULT '' COMMENT '读取SN',
	`uid` VARCHAR (30) DEFAULT '' COMMENT '读取UID',
	`mac_cloud` VARCHAR (30) DEFAULT '' COMMENT '读取MAC',
	`check_sn_uid` VARCHAR (30) DEFAULT '' COMMENT '检查SN_UID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t040_test_report` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rn` varchar(30) NOT NULL,
  `start_test_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `end_test_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fixture_id` varchar(30) DEFAULT '' COMMENT '测试设备编号',
  `operator_id` varchar(30) DEFAULT '' COMMENT '操作员编号',
  `software_version` varchar(30) DEFAULT '' COMMENT '产测软件版本',
  `spec_id` int(11) DEFAULT NULL COMMENT '测试规格编号',
  `ng_items` varchar(255) DEFAULT '' COMMENT 'NG测项列表',
  `test_result` varchar(30) NOT NULL COMMENT '测试结果',
  `read_tagnumber` varchar(30) DEFAULT '',
  `write_tagnumber` varchar(30) DEFAULT '',
  `fw_version` varchar(32) DEFAULT '' COMMENT '产品固件版本号',
  `product_voltage_reading` float DEFAULT NULL COMMENT '成品电压读数',
  `product_audio` varchar(16) DEFAULT '' COMMENT '声音检查',
  `product_led` varchar(16) DEFAULT '' COMMENT 'Led检查',
  `product_mic_max_abs` varchar(16) DEFAULT '' COMMENT '成品麦克风 2',
  `product_mic_delta` varchar(16) DEFAULT '' COMMENT '成品麦克风 2',
  `product_mic` varchar(16) DEFAULT '' COMMENT '1',
  `product_mic_amp` float DEFAULT NULL COMMENT '1',
  `product_mic_power` float DEFAULT NULL COMMENT '1',
  `product_button` varchar(16) DEFAULT '' COMMENT '成品按键检查',
  `product_motion` varchar(16) DEFAULT '' COMMENT '成品Motion',
  `product_mac_address` varchar(32) DEFAULT '' COMMENT 'MAC地址 1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t050_test_report` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rn` varchar(30) NOT NULL,
  `start_test_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `end_test_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fixture_id` varchar(30) DEFAULT '' COMMENT '测试设备编号',
  `operator_id` varchar(30) DEFAULT '' COMMENT '操作员编号',
  `software_version` varchar(30) DEFAULT '' COMMENT '产测软件版本',
  `spec_id` int(11) DEFAULT NULL COMMENT '测试规格编号',
  `ng_items` varchar(255) DEFAULT '' COMMENT 'NG测项列表',
  `test_result` varchar(30) NOT NULL COMMENT '测试结果',
  `read_tagnumber` varchar(30) DEFAULT '',
  `write_tagnumber` varchar(30) DEFAULT '',
  `fw_version` varchar(32) DEFAULT '' COMMENT '产品固件版本号',
  `product_temperature_reading` float DEFAULT NULL COMMENT '成品温度读数',
  `product_light_reading` varchar(16) DEFAULT '' COMMENT '成品亮度读数',
  `product_vlc_video_check` varchar(16) DEFAULT '' COMMENT '成品视频检查 2',
  `product_ir_check` varchar(16) DEFAULT '' COMMENT '成品IR-CUT检查 2',
  `up_packet_loss` float DEFAULT NULL COMMENT '上行丢包率',
  `up_rate` float DEFAULT NULL COMMENT '上行速率',
  `down_packet_loss` float DEFAULT NULL COMMENT '下行丢包率',
  `down_rate` float DEFAULT NULL COMMENT '下行速率',
  `rf_result_mHz` float DEFAULT NULL COMMENT 'RF频率值',
  `rf_result_db` float DEFAULT NULL COMMENT 'RF db值',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t060_test_report` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rn` varchar(30) NOT NULL,
  `start_test_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `end_test_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fixture_id` varchar(30) DEFAULT '' COMMENT '测试设备编号',
  `operator_id` varchar(30) DEFAULT '' COMMENT '操作员编号',
  `software_version` varchar(30) DEFAULT '' COMMENT '产测软件版本',
  `spec_id` int(11) DEFAULT NULL COMMENT '测试规格编号',
  `ng_items` varchar(255) DEFAULT '' COMMENT 'NG测项列表',
  `test_result` varchar(30) NOT NULL COMMENT '测试结果',
  `read_tagnumber` varchar(30) DEFAULT '',
  `write_tagnumber` varchar(30) DEFAULT '',
  `fw_version` varchar(32) DEFAULT '' COMMENT '固件版本号',
  `sn` varchar(32) DEFAULT '' COMMENT '写SN码',
  `uid` varchar(32) DEFAULT '' COMMENT '写UID码',
  `mac` varchar(32) DEFAULT '' COMMENT '写MAC地址',
  `print_sn` varchar(32) DEFAULT '' COMMENT '打印SN 2',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t070_test_report` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rn` varchar(30) NOT NULL,
  `start_test_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `end_test_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fixture_id` varchar(30) DEFAULT '' COMMENT '测试设备编号',
  `operator_id` varchar(30) DEFAULT '' COMMENT '操作员编号',
  `software_version` varchar(30) DEFAULT '' COMMENT '产测软件版本',
  `spec_id` int(11) DEFAULT NULL COMMENT '测试规格编号',
  `ng_items` varchar(255) DEFAULT '' COMMENT 'NG测项列表',
  `test_result` varchar(30) NOT NULL COMMENT '测试结果',
  `read_tagnumber` varchar(30) DEFAULT '',
  `write_tagnumber` varchar(30) DEFAULT '',
  `mcu_version` varchar(32) DEFAULT '' COMMENT 'MCU 版本',
  `fw_version` varchar(32) DEFAULT '' COMMENT 'FW版本',
  `hw_version` varchar(32) DEFAULT '' COMMENT 'HW版本',
  `sensitivity_test` varchar(32) DEFAULT '' COMMENT '灵敏度测试',
  `check_sn` varchar(32) DEFAULT '' COMMENT '检查SN',
  `check_mac` varchar(32) DEFAULT '' COMMENT '检查MAC',
  `check_uid` varchar(32) DEFAULT '' COMMENT '检查UID',
  `check_fw_version` varchar(32) DEFAULT '' COMMENT '检查FW版本',
  `check_mcu_version` varchar(32) DEFAULT '' COMMENT '检查MCU版本',
  `check_hw_version` varchar(32) DEFAULT '' COMMENT '检查HW版本',
  `final_photo` varchar(255) DEFAULT '' COMMENT '测试检查拍摄照片',
  `final_battery_level` float DEFAULT NULL COMMENT '检查电池电量',
  `final_reset` varchar(16) DEFAULT '' COMMENT '恢复出厂设置',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 版本信息标准
CREATE TABLE IF NOT EXISTS `standard_version` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fw_version` varchar(30) DEFAULT '',
  `hw_version` varchar(30) DEFAULT '',
  `mcu_version` varchar(30) DEFAULT '',
  `rn_length` INTEGER DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `xdc01_management`.`standard_version` (`id`, `firmware_version`, `hardware_version`, `mcu_version`, `rn_length`) VALUES ('1', '1056', '6', '0.37', '11');


CREATE TABLE `spec_max` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `voltage_wifi` float DEFAULT NULL COMMENT 'Wi-Fi模组电压',
  `voltage_vcc_core` float DEFAULT NULL COMMENT '电压_vcc_core',
  `voltage_sensor1` float DEFAULT NULL COMMENT '电压传感器1',
  `voltage_sensor2` float DEFAULT NULL COMMENT '电压传感器2',
  `voltage_rtc` float DEFAULT NULL COMMENT '电压_rtc',
  `voltage_vcc` float DEFAULT NULL COMMENT 'vcc电压',
  `voltage_mcu` float DEFAULT NULL COMMENT 'MCU电压',
  `voltage_ddr` float DEFAULT NULL COMMENT 'DDR电压',
  `work_current` float DEFAULT NULL COMMENT '工作电流',
  `charge_current` float DEFAULT NULL COMMENT '充电电流',
  `standby_current` float DEFAULT NULL COMMENT '漏电流',
  `ping_rtt` float DEFAULT NULL COMMENT 'ping平均往返时间',
  `light` float DEFAULT NULL COMMENT '亮度值',
  `battery_voltage` float DEFAULT NULL COMMENT '电池电压',
  `cpu_temperature` float DEFAULT NULL COMMENT 'CPU温度',
  `wifi_up_loss` float DEFAULT NULL COMMENT '上行丢包率',
  `wifi_up_rate` float DEFAULT NULL COMMENT '上行速率',
  `wifi_down_loss` float DEFAULT NULL COMMENT '下行丢包率',
  `wifi_down_rate` float DEFAULT NULL COMMENT '下行速率',
  `rf_tx_frenquency` float DEFAULT NULL COMMENT 'RF频率值',
  `rf_tx_power` float DEFAULT NULL COMMENT 'RF功率值',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `spec_min` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `voltage_wifi` float DEFAULT NULL COMMENT 'Wi-Fi模组电压',
  `voltage_vcc_core` float DEFAULT NULL COMMENT '电压_vcc_core',
  `voltage_sensor1` float DEFAULT NULL COMMENT '电压传感器1',
  `voltage_sensor2` float DEFAULT NULL COMMENT '电压传感器2',
  `voltage_rtc` float DEFAULT NULL COMMENT '电压_rtc',
  `voltage_vcc` float DEFAULT NULL COMMENT 'vcc电压',
  `voltage_mcu` float DEFAULT NULL COMMENT 'MCU电压',
  `voltage_ddr` float DEFAULT NULL COMMENT 'DDR电压',
  `work_current` float DEFAULT NULL COMMENT '工作电流',
  `charge_current` float DEFAULT NULL COMMENT '充电电流',
  `standby_current` float DEFAULT NULL COMMENT '漏电流',
  `ping_rtt` float DEFAULT NULL COMMENT 'ping平均往返时间',
  `light` float DEFAULT NULL COMMENT '亮度值',
  `battery_voltage` float DEFAULT NULL COMMENT '电池电压',
  `cpu_temperature` float DEFAULT NULL COMMENT 'CPU温度',
  `wifi_up_loss` float DEFAULT NULL COMMENT '上行丢包率',
  `wifi_up_rate` float DEFAULT NULL COMMENT '上行速率',
  `wifi_down_loss` float DEFAULT NULL COMMENT '下行丢包率',
  `wifi_down_rate` float DEFAULT NULL COMMENT '下行速率',
  `rf_tx_frenquency` float DEFAULT NULL COMMENT 'RF频率值',
  `rf_tx_power` float DEFAULT NULL COMMENT 'RF功率值',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE change_mode (
	`id` INT (11) NOT NULL AUTO_INCREMENT,
	`sn` VARCHAR (30) NOT NULL,
	`firmware` VARCHAR (30) DEFAULT '' COMMENT 'FW版本',
	`start_test_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`end_test_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`test_result` VARCHAR (30) NOT NULL COMMENT '测试结果',
	`wifi_mode` VARCHAR (30) NOT NULL,
	`test_file` VARCHAR (30) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

-- 包装
CREATE TABLE IF NOT EXISTS `packing_list_report` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `camera_sn` varchar(30) DEFAULT '',
  `carton_box_number` varchar(30) DEFAULT '' COMMENT '大包装箱号码',
  `kit_box_number` varchar(30) DEFAULT '' COMMENT '白盒号码',
  `order_info` varchar(45) DEFAULT '' COMMENT '订单号',
  `shipping_date` varchar(30) DEFAULT '' COMMENT 'PC工具上填写的出货日期',
  `kit_box_time` varchar(30) DEFAULT '' COMMENT '装白盒的时间',
  `carton_box_time` varchar(30) DEFAULT '' COMMENT '扫外箱条码的时间',
  `remark` varchar(255) DEFAULT '' COMMENT '出货备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `camera_sn` (`camera_sn`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE USER 'rckxdc01'@'%' IDENTIFIED BY '2022xdc01';
GRANT SELECT, INSERT ON xdc01_management.* TO 'rckxdc01'@'%';